#!/bin/bash

systemctl enable agent_protocol_splitter.service communication_link.service micrortps_agent.service px4_mavlink_ctrl.service mavlink-router.service mesh-init.service mesh.service mesh_pub.service depthai_ctrl.service navigation.service control_interface.service mocap_pose.service

if [ -e /etc/systemd/system/mission_engine.service ]; then
    systemctl enable mission_engine.service
fi

systemctl enable mission-data-recorder.service

exit 0
