#!/bin/bash

systemctl enable agent_protocol_splitter.service communication_link.service micrortps_agent.service px4_mavlink_ctrl.service mavlink-router.service mesh-init.service mesh.service mesh_pub.service depthai_ctrl.service
