#!/bin/bash

systemctl disable agent_protocol_splitter.service micrortps_agent.service mavlink-router.service
systemctl disable mesh-init.service mesh.service mesh_pub.service
systemctl disable communication_link.service mission_engine.service mission-data-recorder.service
systemctl disable update_agent.service ota_update.service
systemctl disable mocap_pose.service
systemctl disable navigation.service control_interface.service octomap_server2.service bumper.service
systemctl disable depthai_ctrl.service

exit 0
